### ISSUE TITLE
Auto-indent

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#120] opened 2020-01-25 06:56 UTC
**Describe the bug**
Auto-indent used to work (when I type a opening brace and press enter, it would always auto-tab.) It doesn't work on Mac now, though. I'm using the dev branch release.

**To Reproduce**

**Expected behavior**
auto-tab

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ouuan** [comment] 2020-01-25 08:45
Are you sure auto-indent failed just because of different versions instead of different preferences / different operations?

**Comment by coder3101** [comment] 2020-01-25 18:07
The Editor will always use tabs to indent. If you want to use spaces to indent enable `Always Replace Tabs with Spaces`. I can confirm that this works as expected on `dev` branch.

**Comment by ouuan** [comment] 2020-01-29 09:01
> The Editor will always use tabs to indent. If you want to use spaces to indent enable `Always Replace Tabs with Spaces`. I can confirm that this works as expected on `dev` branch.

Does he mean auto-tab uses tabs instead of spaces? He just said "auto-tab doesn't work", and I can't reproduce it.

**Comment by ouuan** [comment] 2020-01-29 09:02
@testitem Please make sure this still happens and give clear descriptions (how to reproduce it?).

**Comment by ouuan** [comment] 2020-01-30 01:36
If no one is answering me, I'll close this in 24 hours.

**Comment by ouuan** [comment] 2020-01-30 01:43
@testitem You should answer others' questions, otherwise don't expect others will answer your questions.

**Comment by coder3101** [comment] 2020-01-31 18:24
I will check it now only. Building dev branch on Catalina and let you know.

**Comment by coder3101** [comment] 2020-01-31 19:11
Confirmed. It is working on master branch!

**Comment by testitem** [comment] 2020-02-01 08:11
It will auto-indent if you turn on "Automatically close opening braces", oddly. But the "automatically close opening braces" functionality is absolutely terrible (because of QCodeEditor's closing brace removal.)

**Comment by coder3101** [comment] 2020-02-01 12:37
> It will auto-indent if you turn on "Automatically close opening braces", oddly. But the "automatically close opening braces" functionality is absolutely terrible (because of QCodeEditor's closing brace removal.)

That may deserve its own issue, and @ouuan is already working on an Editor Widget, a fork of QCodeEditor that should fix all the issues with QCodeEditor.

**Comment by ouuan** [comment] 2020-02-01 12:59
OK. You should have provided your settings in the issue.

**Comment by ouuan** [comment] 2020-02-01 15:38
> > It will auto-indent if you turn on "Automatically close opening braces", oddly. But the "automatically close opening braces" functionality is absolutely terrible (because of QCodeEditor's closing brace removal.)
> 
> That may deserve its own issue, and @ouuan is already working on an Editor Widget, a fork of QCodeEditor that should fix all the issues with QCodeEditor.

I'm finished, you can cherry-pick what you need right now, or merge after everything is OK.

**Comment by ouuan** [comment] 2020-02-01 15:39
BTW, the new test cases UI seems stable now.

**Comment by coder3101** [comment] 2020-02-01 16:42
> BTW, the new test cases UI seems stable now.

Okay cool, after I merge the Mac DMG thing, I will merge the dev branch, if however you have already started implementing some new stuff then please let me know upon which commit hash should I merge to master?

**Comment by coder3101** [comment] 2020-02-08 05:55
Is it fixed now?

**Comment by coder3101** [comment] 2020-02-08 05:55
Your comment referenced above is already in stable release

**Closed** 2020-02-08 07:05 UTC
Labels: bug, low_priority, macOs
