### ISSUE TITLE
Scrolling doesn't work in the "Test cases" subwindow when the cursor is in a textbox

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor#137] opened 2020-01-30 11:05 UTC
**Describe the bug**
RT

**To Reproduce**
1. Put cursor in a textbox of the Test cases.
2. Try to scroll; it doesn't work.

**Expected behavior**
For the entire "Test cases" window to scroll, allowing easy navigation between test cases.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ouuan** [comment] 2020-01-30 11:16
Please don't emphasize Mac again and again, Qt is a cross-platform framework, it's Qt's feature/bug unless there is something like `#ifdef Q_OS_WIN` in the codes.

**Comment by testitem** [comment] 2020-01-31 04:13
well how should i know whether or not the bug is present on windows or linux

**Comment by ouuan** [comment] 2020-01-31 04:17
Because you don't know whether or not the bug is present on Windows or Linux, you shouldn't put it in the title, you should put it in the issue template instead.

**Comment by ouuan** [comment] 2020-01-31 04:19
Put it in the title means "this issue only happens on a certain OS", put it in the description will provide information to help us find the reason of this bug.

**Comment by ouuan** [comment] 2020-01-31 04:19
For this certain issue, the scroll works correctly on Manjaro KDE 18.1.5.

**Comment by testitem** [comment] 2020-01-31 04:28
> Put cursor in a textbox of the Test cases.

It doesn't work when the cursor is in a textbox, because cp-editor is trying to scroll the textbox instead of the entire Test cases window.

**Comment by ouuan** [comment] 2020-01-31 04:44
The scroll part is not implemented in CP Editor, so if it's a bug, it's a bug with Qt.

**Comment by ouuan** [comment] 2020-02-16 13:06
@coder3101 Can you confirm this on the latest version?

**Comment by coder3101** [comment] 2020-02-16 13:13
I don't have a machine now, will confirm when I get home!

**Comment by coder3101** [comment] 2020-02-16 17:51
Hey, I can confirm that all the scroll bars are coming and are as expected. I can't imagine what @testitem is saying. Which version you faced this issue? In latest beta, there is no such issue. Try using latest beta image of mac. I am closing this because i feel that it has been fixed. If you are able to reproduce it again, please open a new issue and strictly follow the template. OS, Version of OS, App Version, Clear and Concise description of the issue. If you can't take 2 minute to write a good issue, how do you expect us to use 2 hours to solve them for you.

**Closed by coder3101** 2020-02-16 17:51 UTC
Labels: bug, macOs
