### ISSUE TITLE
Editor crashed when the program inside had memory violations

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [coder3101/cp-editor#164] opened 2020-02-07 07:35 UTC
**Describe the bug**
The program I've coded violates memory (it has a bad iterator), and instead of killing the process, the editor simply crashed.

**To Reproduce**
Since the editor crashed, the program in question is lost forever ...

**Expected behavior**
The editor should kill the process, instead of crashing itself.

**Screenshots**
It's just the classic windows crash site.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (nothing to do with the crash)
 - Version  79.0.3945.130

**Smartphone (please complete the following information):**
 Not applicable
**Additional context**
Not applicable

**Comment by coder3101** [comment] 2020-02-07 07:53
Could you post a simple minimalist example of code that you ran and did a memory violation?

**Comment by ouuan** [comment] 2020-02-07 08:15
Are you sure it's caused by your codes? I met a segmentation fault yesterday, and I haven't found out the reason. What else had you done before it crashed? Were you running your code on a very large test case?

**Comment by coder3101** [comment] 2020-02-07 08:46
> Are you sure it's caused by your codes? I met a segmentation fault yesterday, and I haven't found out the reason. What else had you done before it crashed? Were you running your code on a very large test case?

Yet another reason for me to quickly complete the log system. Its almost done now I have to call log for every functions and it becomes really painful to do it now. @Razdeep and @ouuan could you log your own codes. Use dev branch see how i have logged some stuffs

**Comment by coder3101** [comment] 2020-02-07 08:48
Yes as far as i know your code is compiled and run as a child process, there is no way that a child process failure will cause error to application!

**Comment by Ravenclaw-OIer** [comment] 2020-02-08 00:53
Killing the process does not help, so I think the it tried to perform write operation to some memory occupied by the editor. (I know nearly nothing about the hardware stuff, so please tutor me here)

Sent from Mail for Windows 10

**Comment by ouuan** [comment] 2020-02-08 01:46
BTW, since the browser has nothing to do with the crash, you should provide the version of CP Editor.

**Comment by Ravenclaw-OIer** [comment] 2020-02-08 02:42
I am using CP editor 5.8.1.

(By the way, you should change that template, I kept fighting with the bot for a long time to make it remove the wontfix label just because I thought the browser is useless and I removed that part.)

Sent from Mail for Windows 10

**Comment by ouuan** [comment] 2020-02-08 02:51
You should delete that line only, instead of the whole "Desktop (please complete the following information):" part.

**Comment by Ravenclaw-OIer** [comment] 2020-02-08 04:52
> Could you post a simple minimalist example of code that you ran and did a memory violation?

It was like 150+ lines of code, and I did not enable the autosave feature, so it's hard to reproduce the bug.

Side note: The bad iterater triggered a dead loop. I checked taskmgr and found that the CPU usage of editor rose to very high (~40%), and remained there after I deliberately killed `sol.exe`.

**Comment by coder3101** [comment] 2020-02-08 05:52
> I think the it tried to perform write operation to some memory occupied by the editor.

Not possible, any process does not have access to other process memory directly. Unless the process runs as root/Admin and was deliberately programmed to change memory bytes. I believe you didn't programmed something like this so, this is ruled out. Meanwhile you should enable Autosave and if you encounter this error again, please share the code here. If we are able to reproduce it ourselves, we will commit a patch and reference this issue. It remains a high priority issue! 

Thanks for reporting this
Happy Competitive Programming!

**Comment by coder3101** [comment] 2020-02-12 18:17
I think it was caused by large `stderr` and `stdout` of process in execution. As discussed and confirmed in telegram, Did you fixed it already @ouuan ? I think a release was made fixing this!

**Comment by ouuan** [comment] 2020-02-13 00:26
> I think it was caused by large `stderr` and `stdout` of process in execution. As discussed and confirmed in telegram, Did you fixed it already @ouuan ? I think a release was made fixing this!

That was the reason of the person asked in tg, not mine.

**Comment by ouuan** [comment] 2020-02-13 05:18
@Ravenclaw-OIer Did it crash right after the run began or after a period (a couple of seconds)? Were there lots of outputs (either `stdout` or `stderr`)?

**Comment by Ravenclaw-OIer** [comment] 2020-02-13 07:13
After a period of time and Yes, there was a huge number of stderr. 

Sent from Mail for Windows 10

**Comment by ouuan** [comment] 2020-02-13 07:31
So I think that was because of too large stderr, and in the latest version, the length is limited.

Close this because only I met unexpected crash without large stderr and I can't reproduce it, maybe I was wrong.

**Closed by ouuan** 2020-02-13 07:31 UTC
Labels: bug, high_priority, on-beta, on-stable, windows

**Comment by ouuan** [comment] 2020-03-02 17:05
I believe the crash I met is fixed in 7d146dab14b2ce361b50920fe6469d45f265d3fb.
